site_name: Supercam Labs
site_url: https://supercam.github.io/greybox
nav:
    - Home: index.md
    - GitHub: https://github.com/supercam/greybox
    - Projects: 
      - projects.md
    - Professional Project One-Pagers:
      - Mobile Device Management: proj_1a_cloud_mdm.md
      - SCCM Application Deployments: proj_1b_Sccm_app_deploy.md
      - Dynamic Distribution Lists in Office 365: proj_1c_ddl_o365.md
      - Managed Identity in AzureAD: proj_1d_cloud_identity.md
      - Building an offsite IDF: proj_1e_idf.md
      - Jira Cloud Management: proj_1f_Jira_cloud_mgmt.md
    - Personal Projects:
      - Homelab Server: lab_1a_labSpace.md
      - Perforce Server: lab_1b_studioPerforce.md
      - LAMP Server: lab_1c_lampServer.md
      - Technical Documentation Project: lab_1d_techdocs.md
      - PowerShell Scripts: https://github.com/supercam/greybox/tree/main/homelab_platform/powershell/operations
    - Reference:
      - License: license.md


repo_url: https://github.com/supercam/

theme:
  palette: 
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: yellow
      accent:
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  language: en
  name: material

copyright: Copyright &copy; 2023 SuperCam Labs

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
