site_name: Supercam Labs
site_url: https://supercam.github.io/greybox
nav:
    - Home: index.md
    - GitHub: https://github.com/supercam/greybox
    - Projects: 
      - projects.md
    - Professional Project One-Pagers:
      - Mobile Device Management: cloud_mdm.md
      - Dynamic Distribution Lists in Office 365: ddl_o365.md
      - Managed Identity in AzureAD: cloud_identity.md
      - Building an offsite IDF: idf.md
      - Jira Cloud Management: Jira_cloud_mgmt.md
    - Personal Projects:
      - Homelab Server: studio_perforce.md
      - Technical Documentation Project: techdocs.md
      - PowerShell Scripts: https://github.com/supercam/greybox/tree/c1570cdc4630352845ab886bfe1f873d34bb1f4a/homelab_platform/powershell
    - Reference:
      - License: license.md


repo_url: https://github.com/supercam/

theme:
  palette: 
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: yellow
      accent:
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  language: en
  name: material

copyright: Copyright &copy; 2023 SuperCam Labs

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
