site_name: Supercam Homelabs
site_url: https://supercam.github.io/greybox
nav:
    - Home: index.md
    - Projects: projects.md
    - Mobile Device Management: cloud_mdm.md
    - Dynamic Distribution Lists O365: ddl_o365.md
    - Managed Identity in Azure AD: cloud_identity.md
    - IDF at offsite location: idf.md
    - Technical Documentation: techdocs.md
    - Homelab FileServer with Perforce: studio_perforce.md

theme:
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: light blue 
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
  language: en
  name: material