name: CI_pwsh
on: [workflow_dispatch]

jobs:
    build:
      name: Run PowerShell Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: homelab_platform/powershell/exampleCI.ps1
          shell: pwsh
